### ISSUE TITLE
yamkix deletes the contents of the file if there's a comment on the list name level

### ISSUE THREAD

**Issue by maxdanilov** [looztra/yamkix#29]
Example:
```
---
item: 123
list: # this is a comment that kills it
- a
- b
- c
```

```
yamkix -i file.yml --no-dash-inwards --spaces-before-comment 2 
```

As the result:
```
Traceback (most recent call last):
  File "/usr/local/bin/yamkix", line 378, in <module>
    main()
  File "/usr/local/bin/yamkix", line 374, in main
    format_yaml(parsed_args)
  File "/usr/local/bin/yamkix", line 252, in format_yaml
    ready_for_dump, yaml, dash_inwards, output_file, spaces_before_comment
  File "/usr/local/bin/yamkix", line 274, in yamkix_dump_all
    doc, yaml, dash_inwards, out, spaces_before_comment
  File "/usr/local/bin/yamkix", line 283, in yamkix_dump_one
    process_comments(single_item, column=spaces_before_comment)
  File "/usr/local/bin/yamkix", line 348, in process_comments
    process_single_comment(data, comment, key, column)
  File "/usr/local/bin/yamkix", line 337, in process_single_comment
    data.yaml_add_eol_comment(comment, key, column=column)
  File "/usr/local/bin/yamkix", line 315, in yamkix_add_eol_comment
    self._yaml_add_eol_comment(comment_token, key=key)
  File "/usr/local/lib/python3.7/site-packages/ruamel/yaml/comments.py", line 656, in _yaml_add_eol_comment
    self._yaml_add_comment(comment, value=key)
  File "/usr/local/lib/python3.7/site-packages/ruamel/yaml/comments.py", line 649, in _yaml_add_comment
    self.yaml_value_comment_extend(value, comment)
  File "/usr/local/lib/python3.7/site-packages/ruamel/yaml/comments.py", line 217, in yaml_value_comment_extend
    r[3].extend(comment[0])
TypeError: 'CommentToken' object is not iterable
```
And `file.yml` becomes empty

Without the comment, everything works fine.

I'm using yamkix 0.6.0

**Comment by looztra** [comment]
my bad, that's one of the edge cases I didn't test.

I'm on it

**Comment by looztra** [comment]
fixed in https://github.com/looztra/yamkix/releases/tag/v0.6.1

**Comment by maxdanilov** [comment]
@looztra awesome, thank you for a very quick fix 🙇
